name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build for multiple platforms
        run: make build-all

      - name: Create release archives
        run: |
          cd dist

          # Linux AMD64
          tar -czf fws-linux-amd64.tar.gz fws-linux-amd64

          # Linux ARM64
          tar -czf fws-linux-arm64.tar.gz fws-linux-arm64

          # macOS AMD64
          tar -czf fws-darwin-amd64.tar.gz fws-darwin-amd64

          # macOS ARM64 (Apple Silicon)
          tar -czf fws-darwin-arm64.tar.gz fws-darwin-arm64

          # Generate checksums
          sha256sum *.tar.gz > checksums.txt

      - name: Generate changelog
        id: changelog
        run: |
          # Simple changelog generation
          if [ -f CHANGELOG.md ]; then
            # Extract current version changes
            sed -n "/^## \[${GITHUB_REF#refs/tags/}\]/,/^## \[/p" CHANGELOG.md | head -n -1 > current_changes.md
          else
            echo "Release ${GITHUB_REF#refs/tags/}" > current_changes.md
            echo "" >> current_changes.md
            echo "Automated release build" >> current_changes.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: current_changes.md
          files: |
            dist/*.tar.gz
            dist/checksums.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
